name: ${project.name}
version:  ${project.version}
author: Alkarin

description: Capture the flag event using Arenas
depend: [BattleArena]
main: mc.alk.ctf.CTF
commands:
    ctf:
        aliases: [captureTheFlag]
